on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  release:
    types:
      - created

name: Package CI
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # @v4.3.0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Run tests
        run: npm run test:coverage
      - name: Run linter
        run: npm run check:code
      - name: Run prettifier
        run: npm run check:prettier
      - name: Report Coverage
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # @master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: decentraland/oddish-action@914e7c59e93e708152aa703c50196740c0526c1d # @master
        with:
          access: public
          ## Sign the deployment
          provenance: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
